deployment:
  type: "continuous"
  rate: 1 #seconds

modules: 
  
  # p4p server instance hosting the model input PVs
  p4p_server:
    name: "p4p_server" # overrides the top key
    type: "interface.p4p_server"
    pub: "in_interface"
    sub: 
      - "get_all"
      - "model" # look we can do this now!
    module_args: None # defines what arguments to pass to the module observer, if any this can inform unpacking etc
    config: 
      EPICS_PVA_NAME_SERVERS: "localhost:5075"
      variables:
        # TODO: Expose more of these, preferrably in a more automatic way
        # May be worth adding support for a !include directive to polylithic and LUME model so we can share a single YAML
        # with a full list of input PVs.
        # Alternatively, we could automatically detect input and output PVs.
        QUAD:LI21:221:BCTRL:
          proto: pva
          name: QUAD:LI21:221:BCTRL
        hxr_pulse_intensity:
          proto: pva
          name: hxr_pulse_intensity
          mode: out

  # The model!
  model:
    name: "model"
    type: "model.SurrogateModelFactory"
    pub: "model"          # Publish our outputs to "model"
    sub: "in_interface"   # Inputs defined by "p4p_server"
    module_args: None
    config:
      type: "LocalModelGetter"
      args: 
        model_path: "model/model.py" 
        model_factory_class: "ModelFactory"
